# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# author = Author.create(name: "Stephen King", bio: "One of the most prolific writers in history.", genre_id: 1)
# author = Author.create(name: "Phillip K Dick", bio: "An American writer known for his work in science fiction.", genre_id: 3)
# author = Author.create(name: "H.P. Lovecraft", bio: "an American writer who achieved posthumous fame through his influential works of horror fiction.", genre_id: 1)
# author = Author.create(name: "Isaac Asimov", bio: "An American writer and professor of biochemistry at Boston University.", genre_id: 3)
# author = Author.create(name: "J.R.R. Tolkien", bio: "was an English writer, poet, philologist, and academic, widely regarded as the originator of classic high fantasy.", genre_id: 2)
# author = Author.create(name: "Piers Anthony", bio: "An English-American author in the science fiction and fantasy genres.", genre_id: 2)
book = Book.create(title: "'Salem's Lot", description: "Old World vampires creep into small town rural America.", image: "https://images.penguinrandomhouse.com/cover/9780345806796", author_id:1, genre_id: 1)
book = Book.create(title: "The Stand", description: "Outlines the total breakdown of society after the accidental release of a bioweapon strain of influenza kills off over 99 percent the world's human population.", image: "https://upload.wikimedia.org/wikipedia/en/9/96/The_Stand_cover.jpg", author_id:1, genre_id: 1)
book = Book.create(title: "The Shining", description: "A winter caretaker and his family deal with islolation, the elements, and supernatural horrors in a resort hotel.", image: "https://upload.wikimedia.org/wikipedia/en/4/4c/Shiningnovel.jpg", author_id:1, genre_id: 1)
book = Book.create(title: "The Call of Cthulhu", description: "A narrator recounts various notes and tales of an ancient, aquatic monster.", image:"https://images.gr-assets.com/books/1377787655l/15730101.jpg", author_id: 3, genre_id: 1)
book = Book.create(title: "At the Mountains of Madness", description: "The story details the events of a disastrous expedition to the Antarctic continent in September 1930, and what was found there by a group of explorers.", image:"https://upload.wikimedia.org/wikipedia/en/f/fc/Lovecraft%2C_Mountains_of_Madness.jpg", author_id: 3, genre_id: 1)
book = Book.create(title: "The Shadow Out of Time", description: "Indirectly tells of the Great Race of Yith, an extraterrestrial species with the ability to travel through space and time.", image:"https://upload.wikimedia.org/wikipedia/commons/e/e3/ShadowOutOfTime.jpg", author_id: 3, genre_id: 1)
book = Book.create(title: "Do Androids Dream of Electric Sheep", description: "Detective Rick Deckard in a post-apocalyptic San Francisco as he tracks down runaway androids, who as slaves are forbidden to come back to Earth from the off world colonies.", image:"https://upload.wikimedia.org/wikipedia/en/e/ee/DoAndroidsDream.png", author_id: 2, genre_id: 3)
book = Book.create(title: "A Scanner Darkly", description: "A dystopian Orange County, California, in the then-future of June 1994, and includes an extensive portrayal of drug culture and drug use (both recreational and abusive).", image: "https://upload.wikimedia.org/wikipedia/en/2/27/AScannerDarkly%281stEd%29.jpg", author_id: 2, genre_id: 3)
book = Book.create(title: "The Man in the High Castle", description: "Fifteen years after an alternative ending to World War II, the novel concerns intrigues between the victorious Axis Powers, primarily Imperial Japan and Nazi Germany, as they rule over the former United States.", image:"https://upload.wikimedia.org/wikipedia/en/8/87/Man_in_the_High_Castle_%281st_Edition%29.png", author_id: 2, genre_id: 3)
book = Book.create(title: "I, Robot", description: "A collection of short stories exploring the nature of robot/human relationships.", image:"https://upload.wikimedia.org/wikipedia/en/d/d5/I_robot.jpg", author_id: 4, genre_id: 3)
book = Book.create(title: "The Martian Way and Other Stories", description: "A collection of four sci-fi novellas published in 1955.", image:"https://upload.wikimedia.org/wikipedia/en/6/60/Martian_way.jpg", author_id: 4, genre_id: 3)
book = Book.create(title: "The Gods Themselves", description: "The Gods Themselves is a story of two worlds that are struggling for power and survival, although they have never met.", image:"https://upload.wikimedia.org/wikipedia/en/a/a3/TheGodsThemselves%281stEd%29.jpg", author_id: 4, genre_id: 3)
book = Book.create(title: "The Lord of the Rings: The Fellowship of the Ring", description: "A band of adventurers sets out to destroy a ring of power before it is found by an evil sorcerer.", image:"https://upload.wikimedia.org/wikipedia/en/8/8e/The_Fellowship_of_the_Ring_cover.gif", author_id: 5, genre_id: 2)
book = Book.create(title: "The Lord of the Rings: The Two Towers", description: ".", image:"https://upload.wikimedia.org/wikipedia/en/a/a1/The_Two_Towers_cover.gif", author_id: 5, genre_id: 2)
book = Book.create(title: "The Lord of the Rings: The Return of the King", description: "The quest to destroy the Ring of Power reaches it's exciting conclusion.", image:"https://upload.wikimedia.org/wikipedia/en/1/11/The_Return_of_the_King_cover.gif", author_id: 5, genre_id: 2)
book = Book.create(title: "On A Pale Horse", description: "The book focuses on Zane, a photographer about to commit suicide who instead kills Death and must assume his office.", image:"https://upload.wikimedia.org/wikipedia/en/a/ae/On_A_Pale_Horse_cover_by_Piers_Anthony.jpg", author_id: 6, genre_id: 2)
book = Book.create(title: "Bearing An Hourglass", description: "A man assumes the office of Time, an Incarnation of Immortality that lives backwards.", image:"https://upload.wikimedia.org/wikipedia/en/9/9b/Bearinganhourglass.jpg", author_id: 6, genre_id: 2)
book = Book.create(title: "With a Tangled Skein", description: "A woman assumes the office of Fate, a triune Incarnation of Immortality.", image:"https://upload.wikimedia.org/wikipedia/en/1/19/With_a_Tangled_Skein_by_Piers_Anthony.jpg", author_id: 6, genre_id: 2)

